# Generated by Django 4.2.2 on 2024-10-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(blank=True, default='images/doctor-default.png', null=True, upload_to='images'),
        ),
    ]
